version: '3.8'
services:

  db:
    image: mysql
    container_name: db_ecommerce-sf6
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_ecommerce-sf6
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: php
    container_name: www_ecommerce-sf6
    ports:
      - "8741:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

    ###> symfony/mailer ###
  #mailer:
   # image: schickling/mailcatcher
    #ports:
     # - "1025:25"
      #- "1080:1080"
  ###< symfony/mailer ###

networks:
  dev:


volumes:
  db-data:
